---
title: "I/O and hyperlinks, yearly with `caret()`"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output: 
  html_document:
    df_print: paged
    toc: true
    toc_float: true
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, output_dir = "./outputs")
  })
---
  
```{r settings, echo=FALSE, results= 'hide', message=FALSE}
library(knitr)
library(randomForest)
library(data.table)
#library(stplanr)
library(dplyr)
library(ggplot2)
library(tidyr)
#library(readxl)
#library(httr)
#library(tidyverse)
#library(rgdal)
#library(geospacom)
#library(corrplot)
library(gridExtra)
#library(ggrepel)
#library(igraph)
#library(leaflet)
library(caret)
#library(DataExplorer)
#library(skimr)
library(doParallel)
library(xgboost)
library(rprojroot)
library(directlabels)
library(stringr)
library(plotly)
library(htmlwidgets)

options(scipen=999)

#knitr::opts_knit$set(root.dir = 'C:/Users/nw19521/DataShare/Regional positioning in GVC and networks (Andre Carrascal Incera)')
#setwd("C:/Users/nw19521/DataShare/Regional positioning in GVC and networks (Andre Carrascal Incera)")

# start parallel
cl <- makePSOCKcluster(16)
registerDoParallel(cl)

# This is the project path
path <- find_rstudio_root_file()
```


```{r echo=FALSE, results= 'asis', message=FALSE, warning=FALSE}
# change between all hyperlinks and the ones without the self-links

total.path <- paste(path, "/data_inter/total_sectors.csv", sep = "")

total <- read.csv(total.path)
#total <- read.csv("./data_inter/total_noself.csv")

total$X <- NULL

## this is to keep sectors
# y <- y[V1 %like% "^UK" & V1 %like% "ss15$",]          # keep UK and ss15 rows
# y <- y[, .SD, .SDcols = names(y) %like% "^UK" &       # # keep UK and ss15 columns
#            names(y) %like% "ss15$"| names(y) %like% "V1"]
# dim(y)
# y <- as.matrix(y)
# rownames(y) <- y[,1]
# y <- y[,-1]
```

## Model with `caret()`: train on year t and t + 1 with CV, report accuracy, test on t + 2 (unseen data)
### all variables

```{r , include=TRUE, results= 'markup', message=FALSE, fig.height=15, fig.width=10}

## Train on t

# split the data by year into a list
#by.year <- split(total, total$year)

# CV
tc <- trainControl(method = "cv",
                   number = 10,
                   savePredictions = 'final')

# run the model for every 2 years
years <- 2000:2010

# lapply for formulas
sectors <- as.list(c("ss1", "ss2", "ss3",
             "ss4", "ss5", "ss6",
             "ss8", "ss9", "ss10",
             "ss11", "ss12", "ss13", 
             "ss14", "ss15"))

models <- lapply(sectors, function(x) paste0(x,"  ~ dist + emp_thousands.orig + emp_thousands.dest + pop_density.orig + pop_density.dest")) #hl + 


for (t in years){
  for (m in models){ 
  tplus1 <- t + 1
  set.seed(71)
  model.all <- train(formula(m), 
                 data = total[total$year==t | total$year==tplus1,],
                 trControl = tc,
                 method = "rf", importance = TRUE)
  #paste("model", t + 1, t + 2, sep="_")
  assign(paste0(m ,as.character(t + 1)), model.all)
}
}

# It will create: 2001 (train on 2000-2001) - 2011 (train on 2010)
# I need: 2001 (train on 2000-2001) - 2009 (train on 2008-2009)

# create a list of the above model outputs
fit.model.all <- mget(ls(pattern = "~ dist"))

# rename list elements

## function to keep last characters
substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}

## function to combine first and last characters 
new.names <- function(x){
  paste0(substring((x), 1, 4), 
         ".", 
         substrRight((x), 4))
}

## apply function to list with model outputs
new.names <- lapply(names(fit.model.all), new.names)

## remove white spaces
new.names <- gsub("[[:space:]]", "", new.names)

## rename list elements
names(fit.model.all) <- new.names

# resamples
fit.model.all.res <- resamples(fit.model.all)
summary(fit.model.all.res)

# plot metrics

# TODO: fix the year labels

scales <- list(x=list(relation="free"), y=list(relation="free"))
bwplot(fit.model.all.res, scales=scales)

# plot variable importance

# TODO: fix the year labels
```

```{r , include=TRUE, results= 'markup', message=FALSE}
#lapply(fit.year, function(x) plot(varImp(x), main = names(x)))
lapply(names(fit.model.all), function(x) plot(varImp(fit.model.all[[x]]), main=as.character(x)))
```

```{r , include=TRUE, results= 'markup', message=FALSE, fig.height=15, fig.width=10}

## Test on t + 2

# It will create: 2001 (train on 2000-2001) - 2011 (train on 2010)
# I need: 2001 (train on 2000-2001) - 2009 (train on 2008-2009)

# use the model trained in year t to predict io of year t + 1
years <- (2001:2009)
pred.by.year.all <- data.frame(matrix(NA,nrow=1369, ncol = 0)) #172494 # BECAUSE OF USING 1369, THERE ARE NO DUPLICATES BELOW
for (t in years){
  for (s in sectors){
  t_plus_1 <- t + 1
  pred <- predict(fit.model.all[names(fit.model.all)==paste0(s,".",t)], total[total$year==t_plus_1,])
  pred <- as.data.frame(pred)
  rownames(pred) <- c()
  pred.by.year.all <- cbind(pred.by.year.all, pred)
}}

# change column names to match with total
#names(pred.by.year.all) <- 2002:2010

# wide to long
pred.by.year.all <- gather(pred.by.year.all,key = year,value = predictions,1:126)

# year and sectors variables
pred.by.year.all$sector <- substring(pred.by.year.all$year, 1, 4)
pred.by.year.all$sector <- gsub('\\.', '', pred.by.year.all$sector)
pred.by.year.all$year <- substrRight(pred.by.year.all$year, 4)

# drop 2000 and select variables form total
total.no2000_1 <- total %>% 
  filter(year!=2000 & year!=2001) %>% 
  dplyr::select(id, year, contains("ss"))

  
# # test on ss1
# #NOT TO RUN AS IT AFFECTS NEXT LOOP
# test.pred.by.year.all <- pred.by.year.all %>%
#   dplyr::filter(sector=="ss1")
# test.pred.by.year.all <- unique(test.pred.by.year.all)
# 
# # observed data for ss1
# test.total.no2000_1 <- total.no2000_1 %>%
#   dplyr::select(id, year, ss1)
# 
# # column bind prediction and data  
# pred.by.year.all <- cbind(test.pred.by.year.all, test.total.no2000_1)
# # pred.by.year to list by year
# pred.by.year.all.list <- split(pred.by.year.all, pred.by.year.all$year)
# # calculate metrics for every year
# rf.year.all.metrics <- lapply(pred.by.year.all.list, function(x) postResample(pred = x$predictions,
#                                                                      obs = x$ss1))
# rf.year.all.metrics %>% as.data.frame() %>%
#   round(2) %>%
#   kable()
# 
# # there are 2 columns named year, so I drop one
# pred.by.year.all$year <- NULL

# ggplot(data = pred.by.year.all,aes(x = ss1, y = predictions)) +
#   geom_point(colour = "blue") +
#   geom_abline(intercept = 0, slope = 1, colour = "red") +
#   #geom_vline(xintercept = 23, colour = "green", linetype = "dashed") +
#   facet_wrap(~ year,ncol = 2) +
#   #coord_cartesian(xlim = c(0,50000),ylim = c(0,50000)) +
#   ggtitle("Predicted vs. actual trade by year")

# loop on sectors
rf.year.all.metrics <- 0
for (s in sectors){
  test.pred.by.year.all <- pred.by.year.all %>%
    dplyr::filter(sector==s)
    # BECAUSE OF USING 1369 BEFORE THERE ARE NO DUPLICATES. THIS IS THE DIFF WITH test_t2_sectors.Rmd
    # test.pred.by.year.all <- test.pred.by.year.all %>% 

  # observed data for sector s
  test.total.no2000_1 <- total.no2000_1 %>%
  dplyr::select(id, year, s)
  
  # column bind prediction and data  
  help <- cbind(test.pred.by.year.all, test.total.no2000_1)
  help$year <- NULL
  # pred.by.year to list by year
  pred.by.year.all.list <- split(help, help$year)
  # calculate metrics for every year
  rf.year.all.metrics_ <- lapply(pred.by.year.all.list, function(x) postResample(pred = x$predictions,
                                                                     obs = x[,5]))
  rf.year.all.metrics_ <- rf.year.all.metrics_ %>% 
    as.data.frame() %>%
    tibble::rownames_to_column(var = "metric") %>%
    mutate(sector = s)
  
  rf.year.all.metrics <- rbind(rf.year.all.metrics_, rf.year.all.metrics)
}

sector.order <- c("s1", "s2", "s3", "s4", "s5", "s6","s7", "s8",
              "s9", "s10", "s11", "s12", "s13", "s14", "s15")

rf.year.all.metrics %>%
  dplyr::filter(metric=="Rsquared") %>% 
  dplyr::select(-metric) %>%
  gather(key = "variable", value = "value", -sector) %>%
  mutate(variable = gsub('X', '', variable),
         sector = str_replace(sector, "ss", "s"),
         sector = factor(sector, levels = sector.order)) %>%
  ggplot() + 
  aes(x = as.numeric(variable), y = value) +
  geom_line(aes(color = sector), size = 1) +
  labs(x = "year", y = "Rsquared") +
  geom_dl(aes(label = sector), method = list(dl.combine("first.points", "last.points")), cex = 0.8) +
  theme_minimal()

# to create the interactive plot, name a the above chain
# a<-ggplotly(a)
# out.path <- paste0(path, "/paper/figures/sector_rsquared.html")
# saveWidget(a, out.path, selfcontained = T, libdir = "lib")

out.path <- paste0(path, "/paper/figures/sector_rsquared_.png")
ggsave(filename = out.path)


rf.year.all.metrics %>%
  dplyr::filter(metric=="RMSE") %>% 
  dplyr::select(-metric) %>%
  gather(key = "variable", value = "value", -sector) %>%
  mutate(variable = gsub('X', '', variable),
         sector = str_replace(sector, "ss", "s"),
         sector = factor(sector, levels = sector.order)) %>%
  ggplot() + 
  aes(x = as.numeric(variable), y = value) +
  geom_line(aes(color = sector), size = 1) +
  labs(x = "year", y = "RMSE") +
  geom_dl(aes(label = sector), method = list(dl.combine("first.points", "last.points")), cex = 0.8) +
  theme_minimal()

out.path <- paste0(path, "/paper/figures/sector_rmse.png")
ggsave(filename = out.path)

rf.year.all.metrics %>%
  dplyr::filter(metric=="MAE") %>% 
  dplyr::select(-metric) %>%
  gather(key = "variable", value = "value", -sector) %>%
  mutate(variable = gsub('X', '', variable),
         sector = str_replace(sector, "ss", "s"),
         sector = factor(sector, levels = sector.order)) %>%
  ggplot() + 
  aes(x = as.numeric(variable), y = value) +
  geom_line(aes(color = sector), size = 1) +
  labs(x = "year", y = "MAE") +
  geom_dl(aes(label = sector), method = list(dl.combine("first.points", "last.points")), cex = 0.8) +
  theme_minimal()

out.path <- paste0(path, "/paper/figures/sector_mae.png")
ggsave(filename = out.path)
```


```{r, echo=FALSE, results= 'hide', message=FALSE}
stopCluster(cl)
out.path <- paste(path, "/data_inter/test_t2_sectors_nohl.RData", sep = "")
save(list=ls(),file=out.path)
```